{% set name = "trict" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trict-{{ version }}.tar.gz
  sha256: 593a016ce17d8e6e3d83fa9c732d09ffa44424568a7150d07423f6fec655bca8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - trict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/saskakarsi/trict
  summary: UserDict subclass with extra stuff
  license: MIT
  # License file manually packaged. See: https://github.com/saskakarsi/trict/pull/6
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saskakarsi
